[package]
name = "evt"
version = "0.1.0"
authors = ["Matt Briggs <matt@mattbriggs.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"

[dev-dependencies]
env_logger = "0.8.2"