name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    services:
      postgres:
        image: mbriggs/message-db:latest
        env:
          POSTGRES_PASSWORD: evt
          MESSAGEDB_PASSWORD: message_store
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Env
        run: |
          echo "RUST_LOG=info,debug,warning,error" >> $GITHUB_PATH
          echo "MESSAGE_STORE_URL=postgres://message_store:message_store@localhost:5432" >> $GITHUB_PATH
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
